/**
 *
 * $Id$
 */
package transitiongraph.validation;

import org.eclipse.emf.common.util.EList;

import transitiongraph.Transition;

/**
 * A sample validator interface for {@link transitiongraph.State}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateValidator {
    boolean validate();

    boolean validateId(int value);
    boolean validateOutgoing(EList<Transition> value);
    boolean validateIncoming(EList<Transition> value);
    boolean validateIsFinal(boolean value);
    boolean validateIsInitial(boolean value);
}
