/**
 *
 * $Id$
 */
package de.hu_berlin.ensureII.sre.model.sre.validation;

import de.hu_berlin.ensureII.sre.model.sre.Node;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.hu_berlin.ensureII.sre.model.sre.Concat}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConcatValidator {
    boolean validate();

    boolean validateSubnodes(EList<EList<Node>> value);
}
